import "./image-data-polyfill.js";
import { resize } from "@maker/core-image";
import { PNG } from "pngjs";
import { callGemini, firstInlineImagePart } from "./gemini-client.js";

export interface GenerateImageOptions {
  width?: number;
  height?: number;
}

export interface GeneratedImage {
  width: number;
  height: number;
  /** Raw RGBA pixel bytes, width*height*4 long. */
  data: Uint8ClampedArray;
  /** Human-readable disclosure of how the image was produced. */
  notes: string;
}

const DEFAULT_SIZE = 512;
const MAX_DIMENSION = 2048;
const DEFAULT_MODEL = "gemini-2.5-flash-image";

/** Thrown for a caller-supplied width/height that's not a finite positive integer within MAX_DIMENSION. */
export class InvalidDimensionError extends Error {}

function validateDimension(name: "width" | "height", value: number): void {
  if (!Number.isInteger(value) || value <= 0) {
    throw new InvalidDimensionError(`"${name}" must be a positive integer`);
  }
  if (value > MAX_DIMENSION) {
    throw new InvalidDimensionError(`"${name}" must be at most ${MAX_DIMENSION}`);
  }
}

/**
 * Generates an image from a text prompt via Gemini's image-generation model.
 * Gemini produces images at its own native resolution/aspect ratio (not an
 * arbitrary caller-chosen size), so the decoded PNG is resized to the
 * requested width/height to keep this function's contract stable for callers
 * that expect an exact size back.
 */
export async function generateImage(
  prompt: string,
  options?: GenerateImageOptions,
): Promise<GeneratedImage> {
  const width = options?.width ?? DEFAULT_SIZE;
  const height = options?.height ?? DEFAULT_SIZE;
  validateDimension("width", width);
  validateDimension("height", height);

  const model = process.env.GEMINI_IMAGE_MODEL || DEFAULT_MODEL;
  const response = await callGemini(model, {
    contents: [{ parts: [{ text: prompt }] }],
    generationConfig: { responseModalities: ["IMAGE"] },
  });

  const inline = firstInlineImagePart(response);
  if (!inline) {
    throw new Error("Gemini response did not include a generated image");
  }

  const decoded = PNG.sync.read(Buffer.from(inline.data, "base64"));
  const decodedImage = {
    width: decoded.width,
    height: decoded.height,
    data: new Uint8ClampedArray(
      decoded.data.buffer,
      decoded.data.byteOffset,
      decoded.data.byteLength,
    ),
  };

  const needsResize = decoded.width !== width || decoded.height !== height;
  const finalImage = needsResize
    ? resize(decodedImage as ImageData, { width, height, method: "bilinear" })
    : decodedImage;

  return {
    width,
    height,
    data: finalImage.data,
    notes: needsResize
      ? `Generated by Gemini (model: ${model}) at ${decoded.width}x${decoded.height}, resized to ${width}x${height}.`
      : `Generated by Gemini (model: ${model}).`,
  };
}
