import { describe, expect, it } from "vitest";
import type { VectorPath } from "@maker/core-vector";
import { pathsToGcode, rasterToGcode } from "../src/generate.js";

function solidImage(width: number, height: number, rgba: [number, number, number, number]): ImageData {
  const data = new Uint8ClampedArray(width * height * 4);
  for (let i = 0; i < width * height; i++) {
    data[i * 4] = rgba[0];
    data[i * 4 + 1] = rgba[1];
    data[i * 4 + 2] = rgba[2];
    data[i * 4 + 3] = rgba[3];
  }
  return new ImageData(data, width, height);
}

const PREAMBLE = ["; Generated by maker-image-tools", "G21", "G90"];

describe("pathsToGcode", () => {
  it("emits exact preamble/postamble/format for a simple 2-point path", () => {
    const path: VectorPath = {
      id: "p1",
      commands: [{ type: "M", point: { x: 0, y: 0 } }, { type: "L", point: { x: 10, y: 0 } }],
    };

    const result = pathsToGcode([path]);

    const expected = [
      ...PREAMBLE,
      "G0 X0 Y0",
      "M4 S1000",
      "G1 X10 Y0 F1000",
      "M5",
      "G0 X0 Y0",
      "M5",
    ].join("\n") + "\n";

    expect(result).toBe(expected);
  });

  it("only emits F on the first G1 of a path with 3+ points", () => {
    const path: VectorPath = {
      id: "p1",
      commands: [
        { type: "M", point: { x: 0, y: 0 } },
        { type: "L", point: { x: 10, y: 0 } },
        { type: "L", point: { x: 10, y: 10 } },
      ],
    };

    const result = pathsToGcode([path]);

    const expected = [
      ...PREAMBLE,
      "G0 X0 Y0",
      "M4 S1000",
      "G1 X10 Y0 F1000",
      "G1 X10 Y10",
      "M5",
      "G0 X0 Y0",
      "M5",
    ].join("\n") + "\n";

    expect(result).toBe(expected);
  });

  it("defaults to M4 S1000", () => {
    const path: VectorPath = {
      id: "p1",
      commands: [{ type: "M", point: { x: 0, y: 0 } }, { type: "L", point: { x: 1, y: 1 } }],
    };

    const result = pathsToGcode([path]);

    expect(result).toContain("M4 S1000");
  });

  it("reflects custom power/feedRate/passes/originX/originY", () => {
    const path: VectorPath = {
      id: "p1",
      commands: [{ type: "M", point: { x: 0, y: 0 } }, { type: "L", point: { x: 10, y: 0 } }],
    };

    const result = pathsToGcode([path], {
      power: 500,
      feedRate: 2000,
      passes: 2,
      originX: 5,
      originY: -3,
    });

    const onePass = ["G0 X5 Y-3", "M4 S500", "G1 X15 Y-3 F2000", "M5"];
    const expected = [...PREAMBLE, ...onePass, ...onePass, "G0 X0 Y0", "M5"].join("\n") + "\n";

    expect(result).toBe(expected);
  });

  it("skips a path that flattens to fewer than 2 points", () => {
    const skipPath: VectorPath = {
      id: "skip",
      commands: [{ type: "M", point: { x: 0, y: 0 } }],
    };
    const validPath: VectorPath = {
      id: "valid",
      commands: [{ type: "M", point: { x: 0, y: 0 } }, { type: "L", point: { x: 5, y: 5 } }],
    };

    const result = pathsToGcode([skipPath, validPath]);

    const expected = [
      ...PREAMBLE,
      "G0 X0 Y0",
      "M4 S1000",
      "G1 X5 Y5 F1000",
      "M5",
      "G0 X0 Y0",
      "M5",
    ].join("\n") + "\n";

    expect(result).toBe(expected);
  });

  it("emits only preamble+postamble for an empty paths array", () => {
    const result = pathsToGcode([]);

    const expected = [...PREAMBLE, "G0 X0 Y0", "M5"].join("\n") + "\n";

    expect(result).toBe(expected);
  });
});

describe("rasterToGcode", () => {
  it("emits no G1 moves for an all-white image", () => {
    const image = solidImage(2, 2, [255, 255, 255, 255]);

    const result = rasterToGcode(image);

    expect(result).not.toContain("G1");
    expect(result.endsWith("G0 X0 Y0\nM5\n")).toBe(true);
  });

  it("emits G1 moves with maxPower for an all-black image", () => {
    const image = solidImage(2, 2, [0, 0, 0, 255]);

    const result = rasterToGcode(image, { maxPower: 1000 });

    expect(result).toContain("M4 S1000");
    expect(result).toContain("F1000");
    const g1Lines = result.split("\n").filter((line) => line.startsWith("G1"));
    expect(g1Lines.length).toBeGreaterThan(0);
  });

  it("alternates scan direction between consecutive rows (bidirectional)", () => {
    const image = solidImage(3, 2, [0, 0, 0, 255]);

    const result = rasterToGcode(image);

    // Row 0 (top, worldY=0.1) scans left-to-right: starts at X0, cuts to X0.2.
    expect(result).toContain("G0 X0 Y0.1");
    expect(result).toContain("G1 X0.2 Y0.1 F1000");
    // Row 1 (bottom, worldY=0) scans right-to-left: starts at X0.2, cuts to X0.
    expect(result).toContain("G0 X0.2 Y0");
    expect(result).toContain("G1 X0 Y0 F1000");
  });

  it("merges a run of equal-power pixels into a single G1 line", () => {
    const image = solidImage(5, 1, [0, 0, 0, 255]);

    const result = rasterToGcode(image);

    const g1Lines = result.split("\n").filter((line) => line.startsWith("G1"));
    expect(g1Lines).toEqual(["G1 X0.4 Y0 F1000"]);
  });

  it("emits only preamble+postamble for a zero-dimension image", () => {
    const image = solidImage(0, 0, [0, 0, 0, 0]);

    const result = rasterToGcode(image);

    const expected = [...PREAMBLE, "G0 X0 Y0", "M5"].join("\n") + "\n";

    expect(result).toBe(expected);
  });
});
