import type { VectorPath } from "@maker/core-vector";
import { flattenPath } from "@maker/core-vector";

export interface GcodeGenerationOptions {
  /** mm/min feed rate for cutting/engraving moves. Default 1000. */
  feedRate?: number;
  /** Reserved for future rapid-move tuning; G0 moves carry no F word today. */
  travelFeedRate?: number;
  /** Laser S value (0-1000) used for M4. Default 1000. */
  power?: number;
  /** Number of times to repeat each path before moving to the next. Default 1. */
  passes?: number;
  /** Tolerance passed to flattenPath when converting curves to line segments. Default 0.1. */
  flattenTolerance?: number;
  /** Added to every emitted X coordinate. Default 0. */
  originX?: number;
  /** Added to every emitted Y coordinate. Default 0. */
  originY?: number;
}

export interface RasterGcodeOptions {
  /** mm/min feed rate for engraving moves. Default 1000. */
  feedRate?: number;
  /** Laser S value at full black (darkest pixel). Default 1000. */
  maxPower?: number;
  /** Laser S value at full white that still fires. Default 0. */
  minPower?: number;
  /** Physical size of one pixel, in mm. Default 0.1. */
  pixelSizeMm?: number;
  /** Added to every emitted X coordinate. Default 0. */
  originX?: number;
  /** Added to every emitted Y coordinate. Default 0. */
  originY?: number;
  /** Grayscale value (0-255) at or above which a pixel is skipped entirely. Default 250. */
  whiteThreshold?: number;
}

const PREAMBLE = ["; Generated by maker-image-tools", "G21", "G90"];
const POSTAMBLE = ["G0 X0 Y0", "M5"];

/** Rounds to 3 decimal places and strips trailing zeros / a trailing decimal point. */
function formatCoord(n: number): string {
  let rounded = Math.round(n * 1000) / 1000;
  if (rounded === 0) rounded = 0; // normalize -0 to 0
  const fixed = rounded.toFixed(3);
  return fixed.replace(/\.?0+$/, "") || "0";
}

export function pathsToGcode(paths: VectorPath[], options: GcodeGenerationOptions = {}): string {
  const feedRate = options.feedRate ?? 1000;
  const power = Math.round(options.power ?? 1000);
  const passes = options.passes ?? 1;
  const flattenTolerance = options.flattenTolerance ?? 0.1;
  const originX = options.originX ?? 0;
  const originY = options.originY ?? 0;

  const lines: string[] = [...PREAMBLE];

  for (const path of paths) {
    const points = flattenPath(path, flattenTolerance);
    if (points.length < 2) continue;

    for (let pass = 0; pass < passes; pass++) {
      const first = points[0]!;
      lines.push(`G0 X${formatCoord(first.x + originX)} Y${formatCoord(first.y + originY)}`);
      lines.push(`M4 S${power}`);

      // F is modal in real G-code, so it's only emitted on this first G1 of the path-pass.
      const second = points[1]!;
      lines.push(
        `G1 X${formatCoord(second.x + originX)} Y${formatCoord(second.y + originY)} F${formatCoord(feedRate)}`,
      );

      for (let i = 2; i < points.length; i++) {
        const p = points[i]!;
        lines.push(`G1 X${formatCoord(p.x + originX)} Y${formatCoord(p.y + originY)}`);
      }

      lines.push("M5");
    }
  }

  lines.push(...POSTAMBLE);
  return lines.join("\n") + "\n";
}

export function rasterToGcode(image: ImageData, options: RasterGcodeOptions = {}): string {
  const feedRate = options.feedRate ?? 1000;
  const maxPower = options.maxPower ?? 1000;
  const minPower = options.minPower ?? 0;
  const pixelSizeMm = options.pixelSizeMm ?? 0.1;
  const originX = options.originX ?? 0;
  const originY = options.originY ?? 0;
  const whiteThreshold = options.whiteThreshold ?? 250;

  const lines: string[] = [...PREAMBLE];

  const { width, height, data } = image;

  if (width > 0 && height > 0) {
    let laserOn = false;
    let currentPower = -1;

    for (let y = 0; y < height; y++) {
      // Row 0 (the image's top row) maps to the largest world Y.
      const worldY = originY + (height - 1 - y) * pixelSizeMm;
      const leftToRight = y % 2 === 0;

      const cols: number[] = [];
      if (leftToRight) {
        for (let x = 0; x < width; x++) cols.push(x);
      } else {
        for (let x = width - 1; x >= 0; x--) cols.push(x);
      }

      const powers: number[] = cols.map((x) => {
        const idx = (y * width + x) * 4;
        const r = data[idx] ?? 0;
        const g = data[idx + 1] ?? 0;
        const b = data[idx + 2] ?? 0;
        const luma = 0.299 * r + 0.587 * g + 0.114 * b;
        if (luma >= whiteThreshold) return 0;
        const raw = minPower + ((maxPower - minPower) * (255 - luma)) / 255;
        return Math.round(Math.min(Math.max(raw, minPower), maxPower));
      });

      let i = 0;
      let positioned = false;
      while (i < cols.length) {
        const runPower = powers[i]!;
        let j = i;
        while (j < cols.length && powers[j] === runPower) j++;

        if (runPower === 0) {
          if (j < cols.length) {
            const afterCol = cols[j]!;
            const worldX = originX + afterCol * pixelSizeMm;
            lines.push(`G0 X${formatCoord(worldX)} Y${formatCoord(worldY)}`);
          }
        } else {
          const firstCol = cols[i]!;
          const lastCol = cols[j - 1]!;

          if (!positioned) {
            const worldXFirst = originX + firstCol * pixelSizeMm;
            lines.push(`G0 X${formatCoord(worldXFirst)} Y${formatCoord(worldY)}`);
          }

          if (!laserOn || currentPower !== runPower) {
            lines.push(`M4 S${runPower}`);
            laserOn = true;
            currentPower = runPower;
          }

          const worldXLast = originX + lastCol * pixelSizeMm;
          lines.push(`G1 X${formatCoord(worldXLast)} Y${formatCoord(worldY)} F${formatCoord(feedRate)}`);
        }

        positioned = true;
        i = j;
      }

      lines.push("M5");
      laserOn = false;
    }
  }

  lines.push(...POSTAMBLE);
  return lines.join("\n") + "\n";
}
